"""
BioSync AI - Bio-Nutritional Knowledge Base & Micronutrient Decomposition Engine
Module: nutrition_db.py

Deterministic Ground-Truth Nutrition Database compiled from:
- USDA FoodData Central (FNDDS + SR Legacy)
- OpenFoodFacts Verified Product Registry

Outputs per item:
- Macronutrients: Calories (kcal), Net Carbs (g), Protein (g), Fats (g), Saturated Fat (g), Dietary Fiber (g), Sugar (g)
- Micronutrients & Minerals: Sodium (mg), Potassium (mg), Calcium (mg), Iron (mg), Magnesium (mg)
- Essential Vitamins: Vitamin A (mcg), Vitamin C (mg), Vitamin D (IU), Vitamin B12 (mcg)
- Glycemic Metrics: Glycemic Index (GI), Glycemic Load (GL)
- Portion Scaling Factor
"""

from typing import Dict, Any, Optional, List
import numpy as np


class BioNutritionalDatabase:
    """
    Offline, high-precision nutritional knowledge base providing deterministic
    macro and micronutrient profiles without external API latency.
    """

    NUTRITION_CATALOG: Dict[str, Dict[str, Any]] = {
        # =========================================================
        # 1. RAW PRODUCE (FRUITS & VEGETABLES)
        # =========================================================
        "apple": {
            "displayName": "Fresh Apple",
            "category": "Raw_Produce",
            "standardServing": "1 medium fruit (approx 150g)",
            "servingUnit": "fruit",
            "servingWeightGrams": 150,
            "gi": 36,
            "nutrientsPerServing": {
                "calories": 78,
                "carbohydrates": 20.7,
                "netCarbohydrates": 17.1,
                "fiber": 3.6,
                "sugar": 15.6,
                "proteins": 0.4,
                "fats": 0.3,
                "saturatedFat": 0.05,
                "sodium": 1.5,
                "potassium": 160.5,
                "calcium": 9.0,
                "iron": 0.18,
                "magnesium": 7.5,
                "vitaminA": 4.5,
                "vitaminC": 6.9,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "banana": {
            "displayName": "Ripe Banana",
            "category": "Raw_Produce",
            "standardServing": "1 medium banana (approx 120g)",
            "servingUnit": "banana",
            "servingWeightGrams": 120,
            "gi": 51,
            "nutrientsPerServing": {
                "calories": 105,
                "carbohydrates": 27.0,
                "netCarbohydrates": 23.9,
                "fiber": 3.1,
                "sugar": 14.4,
                "proteins": 1.3,
                "fats": 0.4,
                "saturatedFat": 0.1,
                "sodium": 1.2,
                "potassium": 422.0,
                "calcium": 6.0,
                "iron": 0.31,
                "magnesium": 32.0,
                "vitaminA": 4.0,
                "vitaminC": 10.3,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "orange": {
            "displayName": "Fresh Orange",
            "category": "Raw_Produce",
            "standardServing": "1 medium fruit (approx 130g)",
            "servingUnit": "fruit",
            "servingWeightGrams": 130,
            "gi": 43,
            "nutrientsPerServing": {
                "calories": 62,
                "carbohydrates": 15.4,
                "netCarbohydrates": 12.3,
                "fiber": 3.1,
                "sugar": 12.2,
                "proteins": 1.2,
                "fats": 0.2,
                "saturatedFat": 0.03,
                "sodium": 1.3,
                "potassium": 237.0,
                "calcium": 52.0,
                "iron": 0.13,
                "magnesium": 13.0,
                "vitaminA": 11.0,
                "vitaminC": 70.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "tomato": {
            "displayName": "Fresh Tomato",
            "category": "Raw_Produce",
            "standardServing": "1 medium tomato (approx 120g)",
            "servingUnit": "tomato",
            "servingWeightGrams": 120,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 22,
                "carbohydrates": 4.7,
                "netCarbohydrates": 3.3,
                "fiber": 1.4,
                "sugar": 3.1,
                "proteins": 1.1,
                "fats": 0.2,
                "saturatedFat": 0.04,
                "sodium": 6.0,
                "potassium": 284.0,
                "calcium": 12.0,
                "iron": 0.32,
                "magnesium": 13.0,
                "vitaminA": 50.0,
                "vitaminC": 16.4,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "cucumber": {
            "displayName": "Cucumber",
            "category": "Raw_Produce",
            "standardServing": "1 cup sliced (approx 100g)",
            "servingUnit": "cup",
            "servingWeightGrams": 100,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 15,
                "carbohydrates": 3.6,
                "netCarbohydrates": 3.1,
                "fiber": 0.5,
                "sugar": 1.7,
                "proteins": 0.7,
                "fats": 0.1,
                "saturatedFat": 0.02,
                "sodium": 2.0,
                "potassium": 147.0,
                "calcium": 16.0,
                "iron": 0.28,
                "magnesium": 13.0,
                "vitaminA": 5.0,
                "vitaminC": 2.8,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "carrot": {
            "displayName": "Fresh Carrot",
            "category": "Raw_Produce",
            "standardServing": "1 medium carrot (approx 60g)",
            "servingUnit": "carrot",
            "servingWeightGrams": 60,
            "gi": 39,
            "nutrientsPerServing": {
                "calories": 25,
                "carbohydrates": 5.8,
                "netCarbohydrates": 4.1,
                "fiber": 1.7,
                "sugar": 2.9,
                "proteins": 0.6,
                "fats": 0.1,
                "saturatedFat": 0.02,
                "sodium": 42.0,
                "potassium": 195.0,
                "calcium": 20.0,
                "iron": 0.18,
                "magnesium": 7.0,
                "vitaminA": 509.0,
                "vitaminC": 3.6,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "broccoli": {
            "displayName": "Steamed Broccoli",
            "category": "Raw_Produce",
            "standardServing": "1 cup florets (approx 90g)",
            "servingUnit": "cup",
            "servingWeightGrams": 90,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 31,
                "carbohydrates": 6.0,
                "netCarbohydrates": 3.6,
                "fiber": 2.4,
                "sugar": 1.5,
                "proteins": 2.6,
                "fats": 0.3,
                "saturatedFat": 0.05,
                "sodium": 30.0,
                "potassium": 288.0,
                "calcium": 43.0,
                "iron": 0.66,
                "magnesium": 19.0,
                "vitaminA": 28.0,
                "vitaminC": 81.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "egg": {
            "displayName": "Egg (Boiled / Whole)",
            "category": "Raw_Produce",
            "standardServing": "1 large egg (approx 50g)",
            "servingUnit": "egg",
            "servingWeightGrams": 50,
            "gi": 0,
            "nutrientsPerServing": {
                "calories": 74,
                "carbohydrates": 0.4,
                "netCarbohydrates": 0.4,
                "fiber": 0.0,
                "sugar": 0.2,
                "proteins": 6.3,
                "fats": 5.0,
                "saturatedFat": 1.6,
                "sodium": 62.0,
                "potassium": 63.0,
                "calcium": 28.0,
                "iron": 0.88,
                "magnesium": 6.0,
                "vitaminA": 80.0,
                "vitaminC": 0.0,
                "vitaminD": 44.0,
                "vitaminB12": 0.5,
                "cholesterol": 186.0,
            },
        },

        # =========================================================
        # 2. INDIAN & GLOBAL COOKED MEALS
        # =========================================================
        "dal": {
            "displayName": "Yellow Dal Tadka",
            "category": "Cooked_Dish",
            "standardServing": "1 bowl (approx 200g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 200,
            "gi": 35,
            "nutrientsPerServing": {
                "calories": 180,
                "carbohydrates": 24.0,
                "netCarbohydrates": 17.5,
                "fiber": 6.5,
                "sugar": 1.8,
                "proteins": 11.0,
                "fats": 4.5,
                "saturatedFat": 0.8,
                "sodium": 380.0,
                "potassium": 450.0,
                "calcium": 45.0,
                "iron": 2.8,
                "magnesium": 48.0,
                "vitaminA": 18.0,
                "vitaminC": 6.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "roti": {
            "displayName": "Whole Wheat Roti / Chapati",
            "category": "Cooked_Dish",
            "standardServing": "1 medium roti (approx 40g)",
            "servingUnit": "piece",
            "servingWeightGrams": 40,
            "gi": 62,
            "nutrientsPerServing": {
                "calories": 110,
                "carbohydrates": 22.0,
                "netCarbohydrates": 18.8,
                "fiber": 3.2,
                "sugar": 0.5,
                "proteins": 3.5,
                "fats": 1.2,
                "saturatedFat": 0.2,
                "sodium": 110.0,
                "potassium": 95.0,
                "calcium": 18.0,
                "iron": 1.1,
                "magnesium": 28.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "rice": {
            "displayName": "Steamed White Rice",
            "category": "Cooked_Dish",
            "standardServing": "1 cup cooked (approx 150g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 150,
            "gi": 73,
            "nutrientsPerServing": {
                "calories": 195,
                "carbohydrates": 42.0,
                "netCarbohydrates": 41.4,
                "fiber": 0.6,
                "sugar": 0.1,
                "proteins": 4.1,
                "fats": 0.4,
                "saturatedFat": 0.1,
                "sodium": 2.0,
                "potassium": 55.0,
                "calcium": 16.0,
                "iron": 0.8,
                "magnesium": 19.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "paneer": {
            "displayName": "Paneer Curry",
            "category": "Cooked_Dish",
            "standardServing": "1 bowl (approx 200g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 200,
            "gi": 27,
            "nutrientsPerServing": {
                "calories": 290,
                "carbohydrates": 9.0,
                "netCarbohydrates": 6.8,
                "fiber": 2.2,
                "sugar": 3.5,
                "proteins": 15.0,
                "fats": 22.0,
                "saturatedFat": 11.0,
                "sodium": 440.0,
                "potassium": 210.0,
                "calcium": 320.0,
                "iron": 1.4,
                "magnesium": 22.0,
                "vitaminA": 120.0,
                "vitaminC": 4.5,
                "vitaminD": 15.0,
                "vitaminB12": 0.6,
                "cholesterol": 45.0,
            },
        },
        "sambhar": {
            "displayName": "Vegetable Sambar",
            "category": "Cooked_Dish",
            "standardServing": "1 bowl (approx 200g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 200,
            "gi": 40,
            "nutrientsPerServing": {
                "calories": 140,
                "carbohydrates": 18.0,
                "netCarbohydrates": 13.2,
                "fiber": 4.8,
                "sugar": 2.4,
                "proteins": 6.2,
                "fats": 3.8,
                "saturatedFat": 0.6,
                "sodium": 420.0,
                "potassium": 360.0,
                "calcium": 40.0,
                "iron": 1.8,
                "magnesium": 32.0,
                "vitaminA": 45.0,
                "vitaminC": 9.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "dosa": {
            "displayName": "Plain Dosa",
            "category": "Cooked_Dish",
            "standardServing": "1 piece (approx 100g)",
            "servingUnit": "piece",
            "servingWeightGrams": 100,
            "gi": 77,
            "nutrientsPerServing": {
                "calories": 168,
                "carbohydrates": 29.0,
                "netCarbohydrates": 27.2,
                "fiber": 1.8,
                "sugar": 0.5,
                "proteins": 3.9,
                "fats": 3.7,
                "saturatedFat": 0.7,
                "sodium": 210.0,
                "potassium": 98.0,
                "calcium": 18.0,
                "iron": 1.2,
                "magnesium": 19.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "idli": {
            "displayName": "Steamed Idli (2 pcs)",
            "category": "Cooked_Dish",
            "standardServing": "2 medium idlis (approx 100g)",
            "servingUnit": "plate",
            "servingWeightGrams": 100,
            "gi": 69,
            "nutrientsPerServing": {
                "calories": 130,
                "carbohydrates": 26.0,
                "netCarbohydrates": 24.2,
                "fiber": 1.8,
                "sugar": 0.3,
                "proteins": 4.2,
                "fats": 0.6,
                "saturatedFat": 0.1,
                "sodium": 180.0,
                "potassium": 85.0,
                "calcium": 22.0,
                "iron": 1.0,
                "magnesium": 18.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "biryani": {
            "displayName": "Chicken / Veg Biryani",
            "category": "Cooked_Dish",
            "standardServing": "1 plate (approx 300g)",
            "servingUnit": "plate",
            "servingWeightGrams": 300,
            "gi": 65,
            "nutrientsPerServing": {
                "calories": 480,
                "carbohydrates": 62.0,
                "netCarbohydrates": 58.4,
                "fiber": 3.6,
                "sugar": 2.1,
                "proteins": 22.0,
                "fats": 16.0,
                "saturatedFat": 4.2,
                "sodium": 650.0,
                "potassium": 340.0,
                "calcium": 48.0,
                "iron": 2.4,
                "magnesium": 38.0,
                "vitaminA": 25.0,
                "vitaminC": 4.0,
                "vitaminD": 8.0,
                "vitaminB12": 0.5,
                "cholesterol": 55.0,
            },
        },
        "oats": {
            "displayName": "Rolled Oats Porridge",
            "category": "Cooked_Dish",
            "standardServing": "1 bowl cooked (approx 200g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 200,
            "gi": 55,
            "nutrientsPerServing": {
                "calories": 150,
                "carbohydrates": 27.0,
                "netCarbohydrates": 23.0,
                "fiber": 4.0,
                "sugar": 1.0,
                "proteins": 5.0,
                "fats": 2.5,
                "saturatedFat": 0.4,
                "sodium": 120.0,
                "potassium": 140.0,
                "calcium": 80.0,
                "iron": 1.9,
                "magnesium": 56.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "salad": {
            "displayName": "Mixed Green Salad",
            "category": "Cooked_Dish",
            "standardServing": "1 bowl (approx 150g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 150,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 45,
                "carbohydrates": 8.0,
                "netCarbohydrates": 5.0,
                "fiber": 3.0,
                "sugar": 4.0,
                "proteins": 2.0,
                "fats": 0.5,
                "saturatedFat": 0.1,
                "sodium": 35.0,
                "potassium": 320.0,
                "calcium": 48.0,
                "iron": 1.2,
                "magnesium": 24.0,
                "vitaminA": 180.0,
                "vitaminC": 28.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },

        # =========================================================
        # 3. PACKAGED & CONVENIENCE PRODUCTS
        # =========================================================
        "maggi": {
            "displayName": "Maggi 2-Minute Masala Noodles",
            "category": "Packaged_Product",
            "standardServing": "1 single pack (approx 70g dry)",
            "servingUnit": "pack",
            "servingWeightGrams": 70,
            "gi": 67,
            "brand": "Nestle",
            "nutrientsPerServing": {
                "calories": 380,
                "carbohydrates": 53.5,
                "netCarbohydrates": 49.9,
                "fiber": 3.6,
                "sugar": 2.2,
                "proteins": 8.0,
                "fats": 14.5,
                "saturatedFat": 6.8,
                "sodium": 860.0, # Clinically significant sodium load
                "potassium": 110.0,
                "calcium": 85.0,
                "iron": 3.7,     # Fortified with iron
                "magnesium": 22.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "flour": {
            "displayName": "Whole Wheat Atta / Flour",
            "category": "Packaged_Product",
            "standardServing": "1 cup raw (approx 100g)",
            "servingUnit": "cup",
            "servingWeightGrams": 100,
            "gi": 65,
            "brand": "Aashirvaad",
            "nutrientsPerServing": {
                "calories": 340,
                "carbohydrates": 72.0,
                "netCarbohydrates": 61.0,
                "fiber": 11.0,
                "sugar": 1.5,
                "proteins": 13.0,
                "fats": 1.8,
                "saturatedFat": 0.3,
                "sodium": 5.0,
                "potassium": 360.0,
                "calcium": 34.0,
                "iron": 3.9,
                "magnesium": 138.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "biscuit": {
            "displayName": "Digestive Biscuits",
            "category": "Packaged_Product",
            "standardServing": "2 biscuits (approx 30g)",
            "servingUnit": "serving",
            "servingWeightGrams": 30,
            "gi": 65,
            "brand": "Britannia",
            "nutrientsPerServing": {
                "calories": 140,
                "carbohydrates": 19.5,
                "netCarbohydrates": 17.7,
                "fiber": 1.8,
                "sugar": 5.2,
                "proteins": 2.1,
                "fats": 6.0,
                "saturatedFat": 2.8,
                "sodium": 160.0,
                "potassium": 65.0,
                "calcium": 15.0,
                "iron": 0.8,
                "magnesium": 14.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "chips": {
            "displayName": "Potato Chips",
            "category": "Packaged_Product",
            "standardServing": "1 bag (approx 50g)",
            "servingUnit": "bag",
            "servingWeightGrams": 50,
            "gi": 75,
            "brand": "Lay's",
            "nutrientsPerServing": {
                "calories": 270,
                "carbohydrates": 26.0,
                "netCarbohydrates": 24.2,
                "fiber": 1.8,
                "sugar": 0.8,
                "proteins": 3.2,
                "fats": 17.5,
                "saturatedFat": 5.2,
                "sodium": 310.0,
                "potassium": 480.0,
                "calcium": 12.0,
                "iron": 0.8,
                "magnesium": 28.0,
                "vitaminA": 0.0,
                "vitaminC": 9.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },

        # =========================================================
        # 4. BEVERAGES & DAIRY PRODUCTS
        # =========================================================
        "curd": {
            "displayName": "Plain Fresh Curd / Dahi",
            "category": "Beverage_Dairy",
            "standardServing": "1 cup (approx 200g)",
            "servingUnit": "cup",
            "servingWeightGrams": 200,
            "gi": 28,
            "nutrientsPerServing": {
                "calories": 122,
                "carbohydrates": 8.8,
                "netCarbohydrates": 8.8,
                "fiber": 0.0,
                "sugar": 8.8,    # Natural lactose
                "proteins": 7.0,
                "fats": 6.5,
                "saturatedFat": 4.0,
                "sodium": 92.0,
                "potassium": 310.0, # High potassium counterbalances sodium
                "calcium": 240.0,   # Rich calcium source
                "iron": 0.1,
                "magnesium": 22.0,
                "vitaminA": 45.0,
                "vitaminC": 1.0,
                "vitaminD": 4.0,
                "vitaminB12": 0.8,  # Critical B12 for nerve & red blood cells
                "cholesterol": 22.0,
            },
        },
        "milk": {
            "displayName": "Cow's Milk (Full Cream)",
            "category": "Beverage_Dairy",
            "standardServing": "1 glass (approx 250ml)",
            "servingUnit": "glass",
            "servingWeightGrams": 250,
            "gi": 31,
            "nutrientsPerServing": {
                "calories": 155,
                "carbohydrates": 12.0,
                "netCarbohydrates": 12.0,
                "fiber": 0.0,
                "sugar": 12.0,
                "proteins": 8.0,
                "fats": 8.5,
                "saturatedFat": 5.2,
                "sodium": 115.0,
                "potassium": 360.0,
                "calcium": 290.0,
                "iron": 0.1,
                "magnesium": 28.0,
                "vitaminA": 65.0,
                "vitaminC": 1.5,
                "vitaminD": 100.0,
                "vitaminB12": 1.1,
                "cholesterol": 28.0,
            },
        },
        "buttermilk": {
            "displayName": "Spiced Buttermilk / Chaas",
            "category": "Beverage_Dairy",
            "standardServing": "1 glass (approx 250ml)",
            "servingUnit": "glass",
            "servingWeightGrams": 250,
            "gi": 25,
            "nutrientsPerServing": {
                "calories": 55,
                "carbohydrates": 5.2,
                "netCarbohydrates": 4.8,
                "fiber": 0.4,
                "sugar": 4.8,
                "proteins": 3.5,
                "fats": 1.8,
                "saturatedFat": 1.1,
                "sodium": 240.0,
                "potassium": 260.0,
                "calcium": 140.0,
                "iron": 0.2,
                "magnesium": 18.0,
                "vitaminA": 22.0,
                "vitaminC": 3.0,
                "vitaminD": 2.0,
                "vitaminB12": 0.4,
                "cholesterol": 6.0,
            },
        },
        "juice": {
            "displayName": "Fruit Juice (Packaged/Fresh)",
            "category": "Beverage_Dairy",
            "standardServing": "1 glass (approx 200ml)",
            "servingUnit": "glass",
            "servingWeightGrams": 200,
            "gi": 68,
            "nutrientsPerServing": {
                "calories": 110,
                "carbohydrates": 26.0,
                "netCarbohydrates": 25.6,
                "fiber": 0.4,
                "sugar": 24.0,   # High free sugars
                "proteins": 0.8,
                "fats": 0.2,
                "saturatedFat": 0.03,
                "sodium": 15.0,
                "potassium": 180.0,
                "calcium": 18.0,
                "iron": 0.4,
                "magnesium": 12.0,
                "vitaminA": 15.0,
                "vitaminC": 35.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "tea": {
            "displayName": "Chai with Milk & Sugar",
            "category": "Beverage_Dairy",
            "standardServing": "1 cup (approx 150ml)",
            "servingUnit": "cup",
            "servingWeightGrams": 150,
            "gi": 45,
            "nutrientsPerServing": {
                "calories": 90,
                "carbohydrates": 14.0,
                "netCarbohydrates": 14.0,
                "fiber": 0.0,
                "sugar": 13.0,
                "proteins": 2.8,
                "fats": 2.6,
                "saturatedFat": 1.6,
                "sodium": 35.0,
                "potassium": 120.0,
                "calcium": 90.0,
                "iron": 0.2,
                "magnesium": 12.0,
                "vitaminA": 20.0,
                "vitaminC": 0.0,
                "vitaminD": 15.0,
                "vitaminB12": 0.3,
                "cholesterol": 8.0,
            },
        },
        "green_tea": {
            "displayName": "Unsweetened Green Tea",
            "category": "Beverage_Dairy",
            "standardServing": "1 cup (approx 200ml)",
            "servingUnit": "cup",
            "servingWeightGrams": 200,
            "gi": 0,
            "nutrientsPerServing": {
                "calories": 2,
                "carbohydrates": 0.2,
                "netCarbohydrates": 0.2,
                "fiber": 0.0,
                "sugar": 0.0,
                "proteins": 0.2,
                "fats": 0.0,
                "saturatedFat": 0.0,
                "sodium": 2.0,
                "potassium": 45.0,
                "calcium": 0.0,
                "iron": 0.02,
                "magnesium": 3.0,
                "vitaminA": 0.0,
                "vitaminC": 0.5,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "avocado": {
            "displayName": "Fresh Avocado",
            "category": "Raw_Produce",
            "standardServing": "1 medium fruit (approx 150g)",
            "servingUnit": "fruit",
            "servingWeightGrams": 150,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 240,
                "carbohydrates": 12.8,
                "netCarbohydrates": 2.8,
                "fiber": 10.0,
                "sugar": 1.0,
                "proteins": 3.0,
                "fats": 22.0,
                "saturatedFat": 3.2,
                "sodium": 10.0,
                "potassium": 727.0,
                "calcium": 18.0,
                "iron": 0.8,
                "magnesium": 44.0,
                "vitaminA": 21.0,
                "vitaminC": 15.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "spinach": {
            "displayName": "Cooked Spinach",
            "category": "Raw_Produce",
            "standardServing": "1 cup cooked (approx 180g)",
            "servingUnit": "cup",
            "servingWeightGrams": 180,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 41,
                "carbohydrates": 6.8,
                "netCarbohydrates": 2.5,
                "fiber": 4.3,
                "sugar": 0.8,
                "proteins": 5.4,
                "fats": 0.5,
                "saturatedFat": 0.1,
                "sodium": 126.0,
                "potassium": 839.0,
                "calcium": 245.0,
                "iron": 6.4,
                "magnesium": 157.0,
                "vitaminA": 943.0,
                "vitaminC": 17.6,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "almond": {
            "displayName": "Raw / Roasted Almonds",
            "category": "Raw_Produce",
            "standardServing": "1 handful (approx 28g / 23 nuts)",
            "servingUnit": "handful",
            "servingWeightGrams": 28,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 164,
                "carbohydrates": 6.1,
                "netCarbohydrates": 2.6,
                "fiber": 3.5,
                "sugar": 1.2,
                "proteins": 6.0,
                "fats": 14.2,
                "saturatedFat": 1.1,
                "sodium": 1.0,
                "potassium": 208.0,
                "calcium": 76.0,
                "iron": 1.0,
                "magnesium": 77.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "peanut": {
            "displayName": "Roasted Peanuts",
            "category": "Raw_Produce",
            "standardServing": "1 handful (approx 28g)",
            "servingUnit": "handful",
            "servingWeightGrams": 28,
            "gi": 14,
            "nutrientsPerServing": {
                "calories": 161,
                "carbohydrates": 4.6,
                "netCarbohydrates": 2.2,
                "fiber": 2.4,
                "sugar": 1.3,
                "proteins": 7.3,
                "fats": 14.0,
                "saturatedFat": 1.9,
                "sodium": 5.0,
                "potassium": 200.0,
                "calcium": 26.0,
                "iron": 1.3,
                "magnesium": 48.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "potato": {
            "displayName": "Boiled / Baked Potato",
            "category": "Raw_Produce",
            "standardServing": "1 medium potato (approx 150g)",
            "servingUnit": "potato",
            "servingWeightGrams": 150,
            "gi": 78,
            "nutrientsPerServing": {
                "calories": 130,
                "carbohydrates": 30.0,
                "netCarbohydrates": 27.5,
                "fiber": 2.5,
                "sugar": 1.2,
                "proteins": 2.8,
                "fats": 0.2,
                "saturatedFat": 0.04,
                "sodium": 8.0,
                "potassium": 610.0,
                "calcium": 15.0,
                "iron": 1.1,
                "magnesium": 35.0,
                "vitaminA": 3.0,
                "vitaminC": 19.5,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "onion": {
            "displayName": "Fresh Onion",
            "category": "Raw_Produce",
            "standardServing": "1 medium onion (approx 110g)",
            "servingUnit": "onion",
            "servingWeightGrams": 110,
            "gi": 15,
            "nutrientsPerServing": {
                "calories": 44,
                "carbohydrates": 10.3,
                "netCarbohydrates": 8.4,
                "fiber": 1.9,
                "sugar": 4.7,
                "proteins": 1.2,
                "fats": 0.1,
                "saturatedFat": 0.03,
                "sodium": 4.0,
                "potassium": 161.0,
                "calcium": 25.0,
                "iron": 0.2,
                "magnesium": 11.0,
                "vitaminA": 0.0,
                "vitaminC": 8.1,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "khichdi": {
            "displayName": "Moong Dal Khichdi",
            "category": "Cooked_Meals",
            "standardServing": "1 medium bowl (approx 250g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 250,
            "gi": 52,
            "nutrientsPerServing": {
                "calories": 260,
                "carbohydrates": 46.0,
                "netCarbohydrates": 40.0,
                "fiber": 6.0,
                "sugar": 2.0,
                "proteins": 8.5,
                "fats": 4.5,
                "saturatedFat": 1.8,
                "sodium": 420.0,
                "potassium": 310.0,
                "calcium": 40.0,
                "iron": 2.2,
                "magnesium": 55.0,
                "vitaminA": 15.0,
                "vitaminC": 2.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 5.0,
            },
        },
        "chole": {
            "displayName": "Chole / Chana Masala (Chickpea Curry)",
            "category": "Cooked_Meals",
            "standardServing": "1 bowl (approx 200g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 200,
            "gi": 38,
            "nutrientsPerServing": {
                "calories": 280,
                "carbohydrates": 38.0,
                "netCarbohydrates": 29.0,
                "fiber": 9.0,
                "sugar": 4.0,
                "proteins": 12.0,
                "fats": 8.0,
                "saturatedFat": 1.2,
                "sodium": 540.0,
                "potassium": 480.0,
                "calcium": 70.0,
                "iron": 3.5,
                "magnesium": 65.0,
                "vitaminA": 35.0,
                "vitaminC": 8.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "rajma": {
            "displayName": "Rajma (Red Kidney Bean Curry)",
            "category": "Cooked_Meals",
            "standardServing": "1 bowl (approx 200g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 200,
            "gi": 35,
            "nutrientsPerServing": {
                "calories": 240,
                "carbohydrates": 34.0,
                "netCarbohydrates": 25.0,
                "fiber": 9.0,
                "sugar": 3.5,
                "proteins": 11.5,
                "fats": 6.5,
                "saturatedFat": 1.0,
                "sodium": 510.0,
                "potassium": 520.0,
                "calcium": 65.0,
                "iron": 3.2,
                "magnesium": 60.0,
                "vitaminA": 25.0,
                "vitaminC": 6.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "chicken_breast": {
            "displayName": "Grilled Chicken Breast",
            "category": "Cooked_Meals",
            "standardServing": "1 piece (approx 150g)",
            "servingUnit": "piece",
            "servingWeightGrams": 150,
            "gi": 0,
            "nutrientsPerServing": {
                "calories": 248,
                "carbohydrates": 0.0,
                "netCarbohydrates": 0.0,
                "fiber": 0.0,
                "sugar": 0.0,
                "proteins": 46.5,
                "fats": 5.4,
                "saturatedFat": 1.5,
                "sodium": 111.0,
                "potassium": 384.0,
                "calcium": 22.0,
                "iron": 1.6,
                "magnesium": 44.0,
                "vitaminA": 18.0,
                "vitaminC": 0.0,
                "vitaminD": 5.0,
                "vitaminB12": 0.6,
                "cholesterol": 128.0,
            },
        },
        "fish": {
            "displayName": "Pan-Seared / Grilled Fish",
            "category": "Cooked_Meals",
            "standardServing": "1 fillet (approx 150g)",
            "servingUnit": "fillet",
            "servingWeightGrams": 150,
            "gi": 0,
            "nutrientsPerServing": {
                "calories": 205,
                "carbohydrates": 0.0,
                "netCarbohydrates": 0.0,
                "fiber": 0.0,
                "sugar": 0.0,
                "proteins": 34.0,
                "fats": 6.8,
                "saturatedFat": 1.3,
                "sodium": 90.0,
                "potassium": 520.0,
                "calcium": 30.0,
                "iron": 0.8,
                "magnesium": 45.0,
                "vitaminA": 40.0,
                "vitaminC": 1.2,
                "vitaminD": 400.0,
                "vitaminB12": 4.2,
                "cholesterol": 75.0,
            },
        },
        "poha": {
            "displayName": "Batata Poha (Flattened Rice)",
            "category": "Cooked_Meals",
            "standardServing": "1 bowl (approx 180g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 180,
            "gi": 64,
            "nutrientsPerServing": {
                "calories": 250,
                "carbohydrates": 44.0,
                "netCarbohydrates": 40.5,
                "fiber": 3.5,
                "sugar": 2.5,
                "proteins": 5.0,
                "fats": 6.0,
                "saturatedFat": 1.2,
                "sodium": 380.0,
                "potassium": 190.0,
                "calcium": 35.0,
                "iron": 4.5,
                "magnesium": 40.0,
                "vitaminA": 15.0,
                "vitaminC": 5.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "upma": {
            "displayName": "Rava Upma (Semolina)",
            "category": "Cooked_Meals",
            "standardServing": "1 bowl (approx 200g)",
            "servingUnit": "bowl",
            "servingWeightGrams": 200,
            "gi": 66,
            "nutrientsPerServing": {
                "calories": 220,
                "carbohydrates": 38.0,
                "netCarbohydrates": 35.0,
                "fiber": 3.0,
                "sugar": 2.0,
                "proteins": 5.5,
                "fats": 5.0,
                "saturatedFat": 1.5,
                "sodium": 410.0,
                "potassium": 160.0,
                "calcium": 30.0,
                "iron": 1.8,
                "magnesium": 30.0,
                "vitaminA": 10.0,
                "vitaminC": 3.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "sandwich": {
            "displayName": "Vegetable Sandwich",
            "category": "Cooked_Meals",
            "standardServing": "1 sandwich (approx 150g)",
            "servingUnit": "sandwich",
            "servingWeightGrams": 150,
            "gi": 56,
            "nutrientsPerServing": {
                "calories": 240,
                "carbohydrates": 32.0,
                "netCarbohydrates": 28.0,
                "fiber": 4.0,
                "sugar": 4.0,
                "proteins": 7.0,
                "fats": 9.0,
                "saturatedFat": 2.8,
                "sodium": 480.0,
                "potassium": 220.0,
                "calcium": 90.0,
                "iron": 1.8,
                "magnesium": 32.0,
                "vitaminA": 35.0,
                "vitaminC": 6.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.2,
                "cholesterol": 8.0,
            },
        },
        "pasta": {
            "displayName": "Cooked Pasta / Macaroni",
            "category": "Packaged_Groceries",
            "standardServing": "1 cup cooked (approx 140g)",
            "servingUnit": "cup",
            "servingWeightGrams": 140,
            "gi": 49,
            "nutrientsPerServing": {
                "calories": 220,
                "carbohydrates": 43.0,
                "netCarbohydrates": 40.5,
                "fiber": 2.5,
                "sugar": 1.0,
                "proteins": 8.0,
                "fats": 1.3,
                "saturatedFat": 0.2,
                "sodium": 1.0,
                "potassium": 61.0,
                "calcium": 10.0,
                "iron": 1.8,
                "magnesium": 25.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "bread": {
            "displayName": "Bread Slices (White / Whole Wheat)",
            "category": "Packaged_Groceries",
            "standardServing": "2 medium slices (approx 60g)",
            "servingUnit": "slices",
            "servingWeightGrams": 60,
            "gi": 72,
            "nutrientsPerServing": {
                "calories": 150,
                "carbohydrates": 28.0,
                "netCarbohydrates": 26.0,
                "fiber": 2.0,
                "sugar": 3.0,
                "proteins": 5.0,
                "fats": 2.0,
                "saturatedFat": 0.4,
                "sodium": 280.0,
                "potassium": 110.0,
                "calcium": 70.0,
                "iron": 1.6,
                "magnesium": 22.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "cereal": {
            "displayName": "Breakfast Cereal (Cornflakes / Muesli)",
            "category": "Packaged_Groceries",
            "standardServing": "1 cup (approx 35g)",
            "servingUnit": "cup",
            "servingWeightGrams": 35,
            "gi": 81,
            "nutrientsPerServing": {
                "calories": 130,
                "carbohydrates": 29.0,
                "netCarbohydrates": 28.0,
                "fiber": 1.0,
                "sugar": 3.2,
                "proteins": 2.5,
                "fats": 0.4,
                "saturatedFat": 0.1,
                "sodium": 240.0,
                "potassium": 55.0,
                "calcium": 5.0,
                "iron": 8.0,
                "magnesium": 12.0,
                "vitaminA": 150.0,
                "vitaminC": 6.0,
                "vitaminD": 40.0,
                "vitaminB12": 1.5,
                "cholesterol": 0.0,
            },
        },
        "peanut_butter": {
            "displayName": "Peanut Butter",
            "category": "Packaged_Groceries",
            "standardServing": "2 tbsp (approx 32g)",
            "servingUnit": "tbsp",
            "servingWeightGrams": 32,
            "gi": 14,
            "nutrientsPerServing": {
                "calories": 188,
                "carbohydrates": 6.9,
                "netCarbohydrates": 4.3,
                "fiber": 2.6,
                "sugar": 2.8,
                "proteins": 8.0,
                "fats": 16.0,
                "saturatedFat": 3.3,
                "sodium": 147.0,
                "potassium": 208.0,
                "calcium": 17.0,
                "iron": 0.6,
                "magnesium": 57.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "chocolate": {
            "displayName": "Dark Chocolate (70% Cacao)",
            "category": "Packaged_Groceries",
            "standardServing": "1 small bar / 4 squares (approx 40g)",
            "servingUnit": "bar",
            "servingWeightGrams": 40,
            "gi": 23,
            "nutrientsPerServing": {
                "calories": 235,
                "carbohydrates": 18.0,
                "netCarbohydrates": 14.0,
                "fiber": 4.0,
                "sugar": 11.5,
                "proteins": 3.2,
                "fats": 17.0,
                "saturatedFat": 10.2,
                "sodium": 8.0,
                "potassium": 280.0,
                "calcium": 28.0,
                "iron": 4.5,
                "magnesium": 90.0,
                "vitaminA": 12.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 1.0,
            },
        },
        "coffee": {
            "displayName": "Black Coffee (Freshly Brewed)",
            "category": "Beverage_Dairy",
            "standardServing": "1 cup (approx 200ml)",
            "servingUnit": "cup",
            "servingWeightGrams": 200,
            "gi": 0,
            "nutrientsPerServing": {
                "calories": 2,
                "carbohydrates": 0.2,
                "netCarbohydrates": 0.2,
                "fiber": 0.0,
                "sugar": 0.0,
                "proteins": 0.3,
                "fats": 0.05,
                "saturatedFat": 0.0,
                "sodium": 5.0,
                "potassium": 116.0,
                "calcium": 4.0,
                "iron": 0.02,
                "magnesium": 7.0,
                "vitaminA": 0.0,
                "vitaminC": 0.0,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
        "coconut_water": {
            "displayName": "Fresh Coconut Water",
            "category": "Beverage_Dairy",
            "standardServing": "1 tender coconut / glass (approx 250ml)",
            "servingUnit": "glass",
            "servingWeightGrams": 250,
            "gi": 35,
            "nutrientsPerServing": {
                "calories": 46,
                "carbohydrates": 9.0,
                "netCarbohydrates": 6.4,
                "fiber": 2.6,
                "sugar": 6.2,
                "proteins": 1.7,
                "fats": 0.5,
                "saturatedFat": 0.4,
                "sodium": 252.0,
                "potassium": 600.0,
                "calcium": 58.0,
                "iron": 0.7,
                "magnesium": 60.0,
                "vitaminA": 0.0,
                "vitaminC": 5.8,
                "vitaminD": 0.0,
                "vitaminB12": 0.0,
                "cholesterol": 0.0,
            },
        },
    }

    # Normalized synonyms mapping
    SYNONYM_MAP: Dict[str, str] = {
        "maggi_2_minute_masala_noodles": "maggi",
        "maggi_noodles": "maggi",
        "nestle_maggi": "maggi",
        "instant_noodles": "maggi",
        "noodles": "maggi",
        "atta": "flour",
        "wheat_flour": "flour",
        "whole_wheat_atta": "flour",
        "aashirvaad_atta": "flour",
        "aashirvaad_wheat_flour": "flour",
        "gehu_atta": "flour",
        "maida": "flour",
        "dahi": "curd",
        "plain_curd": "curd",
        "amul_curd": "curd",
        "amul_dahi": "curd",
        "yogurt": "curd",
        "greek_yogurt": "curd",
        "chaas": "buttermilk",
        "buttermilk": "buttermilk",
        "masala_chaas": "buttermilk",
        "chapati": "roti",
        "phulka": "roti",
        "paratha": "roti",
        "tandoori_roti": "roti",
        "naan": "roti",
        "white_rice": "rice",
        "steamed_rice": "rice",
        "brown_rice": "rice",
        "chawal": "rice",
        "yellow_dal": "dal",
        "dal_tadka": "dal",
        "dal_makhani": "dal",
        "toor_dal": "dal",
        "moong_dal": "dal",
        "fruit_juice": "juice",
        "mango_juice": "juice",
        "orange_juice": "juice",
        "apple_juice": "juice",
        "real_juice": "juice",
        "tropicana": "juice",
        "chai": "tea",
        "masala_chai": "tea",
        "milk_tea": "tea",
        "green_tea": "green_tea",
        "green tea": "green_tea",
        "amul_milk": "milk",
        "whole_milk": "milk",
        "toned_milk": "milk",
        "cow_milk": "milk",
        "lays": "chips",
        "potato_chips": "chips",
        "lays_chips": "chips",
        "wafers": "chips",
        "kurkure": "chips",
        "biscuit": "biscuit",
        "biscuits": "biscuit",
        "parle_g": "biscuit",
        "oreo": "biscuit",
        "cookies": "biscuit",
        "digestive_biscuit": "biscuit",
        "paneer_tikka": "paneer",
        "cottage_cheese": "paneer",
        "chicken": "chicken_breast",
        "grilled_chicken": "chicken_breast",
        "chicken_curry": "chicken_breast",
        "murgh": "chicken_breast",
        "boiled_egg": "egg",
        "eggs": "egg",
        "omelet": "egg",
        "omelette": "egg",
        "apples": "apple",
        "bananas": "banana",
        "oranges": "orange",
        "tomatoes": "tomato",
        "cucumbers": "cucumber",
        "carrots": "carrot",
        "potatoes": "potato",
        "aloo": "potato",
        "onions": "onion",
        "pyaz": "onion",
        "almonds": "almond",
        "badam": "almond",
        "peanuts": "peanut",
        "moongfali": "peanut",
        "chole_bhature": "chole",
        "chana_masala": "chole",
        "chana": "chole",
        "chickpeas": "chole",
        "rajma_chawal": "rajma",
        "kidney_beans": "rajma",
        "cornflakes": "cereal",
        "muesli": "cereal",
        "breakfast_cereal": "cereal",
        "white_bread": "bread",
        "brown_bread": "bread",
        "toast": "bread",
        "dark_chocolate": "chocolate",
        "cadbury": "chocolate",
        "black_coffee": "coffee",
        "espresso": "coffee",
        "cappuccino": "coffee",
        "tender_coconut": "coconut_water",
        "nariyal_pani": "coconut_water",
    }

    @classmethod
    def resolve_key(cls, item_key: str) -> Optional[str]:
        """Resolves fuzzy item keys or synonyms to canonical database keys."""
        if not item_key or not isinstance(item_key, str):
            return None

        # Clean punctuation and normalize
        cleaned = item_key.strip().lower().replace("-", "_").replace(" ", "_")
        cleaned_no_punct = "".join(ch if ch.isalnum() or ch == "_" else "" for ch in cleaned)

        # 1. Direct hit
        if cleaned_no_punct in cls.NUTRITION_CATALOG:
            return cleaned_no_punct

        # 2. Synonym dictionary hit
        if cleaned_no_punct in cls.SYNONYM_MAP:
            return cls.SYNONYM_MAP[cleaned_no_punct]

        # 3. Exact token matching in synonyms & catalog
        tokens = [t for t in cleaned_no_punct.split("_") if len(t) > 2]
        for token in tokens:
            if token in cls.NUTRITION_CATALOG:
                return token
            if token in cls.SYNONYM_MAP:
                return cls.SYNONYM_MAP[token]

        # 4. Substring matching
        for k in cls.NUTRITION_CATALOG.keys():
            if k in cleaned_no_punct or cleaned_no_punct in k:
                return k

        for syn, target in cls.SYNONYM_MAP.items():
            if syn in cleaned_no_punct or cleaned_no_punct in syn:
                return target

        return None

    @classmethod
    def decompose(cls, item_key: str, quantity: float = 1.0) -> Optional[Dict[str, Any]]:
        """
        Calculates exact macro, micro, and glycemic metrics scaled by quantity portion.
        Never hallucinates: returns None if the item is not in the medical catalog.
        """
        canonical_key = cls.resolve_key(item_key)
        if not canonical_key or canonical_key not in cls.NUTRITION_CATALOG:
            return None

        entry = cls.NUTRITION_CATALOG[canonical_key]
        base_nutrients = entry["nutrientsPerServing"]
        q = max(0.1, float(quantity))

        # Scale all nutrients linearly by portion quantity
        scaled_nutrients = {}
        for metric, val in base_nutrients.items():
            scaled_nutrients[metric] = float(np.round(val * q, 2))

        # Compute Glycemic Load = (GI * Net Carbs) / 100
        gi = entry.get("gi", 50)
        net_carbs = scaled_nutrients.get("netCarbohydrates", scaled_nutrients.get("carbohydrates", 0))
        glycemic_load = float(np.round((gi * net_carbs) / 100.0, 1))

        # Clinical GL Classification: Low (<=10), Medium (11-19), High (>=20)
        gl_category = "Low" if glycemic_load <= 10 else ("Medium" if glycemic_load <= 19 else "High")

        return {
            "canonicalKey": canonical_key,
            "displayName": entry["displayName"],
            "category": entry["category"],
            "standardServing": entry["standardServing"],
            "servingUnit": entry["servingUnit"],
            "portionQuantity": q,
            "servingWeightGrams": int(entry["servingWeightGrams"] * q),
            "glycemicIndex": gi,
            "glycemicLoad": glycemic_load,
            "glycemicLoadCategory": gl_category,
            "nutrients": scaled_nutrients,
            "brand": entry.get("brand"),
        }

    @classmethod
    def batch_decompose(cls, item_keys: List[str], quantities: Optional[List[float]] = None) -> List[Dict[str, Any]]:
        """Decomposes multiple detected items in a single high-speed call."""
        results = []
        if quantities is None:
            quantities = [1.0] * len(item_keys)

        for key, q in zip(item_keys, quantities):
            data = cls.decompose(key, q)
            if data:
                results.append(data)

        return results

    @classmethod
    def aggregate_nutrients(cls, decomposed_items: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Calculates aggregated macro and micronutrient totals across a composite meal
        and calculates total Glycemic Load and weighted Glycemic Index.
        """
        if not decomposed_items:
            return {
                "totalWeightGrams": 0,
                "totalGlycemicLoad": 0.0,
                "glycemicLoadCategory": "Low",
                "weightedGlycemicIndex": 0,
                "nutrients": {}
            }

        total_weight = sum(item.get("servingWeightGrams", 0) for item in decomposed_items)
        aggregated_nutrients: Dict[str, float] = {}

        # Accumulate all nutrient quantities
        for item in decomposed_items:
            nutrients = item.get("nutrients", {})
            for key, val in nutrients.items():
                aggregated_nutrients[key] = float(np.round(aggregated_nutrients.get(key, 0.0) + val, 2))

        # Calculate Total Glycemic Load = Sum of item GLs
        total_gl = float(np.round(sum(item.get("glycemicLoad", 0.0) for item in decomposed_items), 1))
        gl_category = "Low" if total_gl <= 10 else ("Medium" if total_gl <= 19 else "High")

        # Weighted Glycemic Index by Net Carbs
        total_net_carbs = aggregated_nutrients.get("netCarbohydrates", aggregated_nutrients.get("carbohydrates", 0.0))
        if total_net_carbs > 0:
            weighted_gi = int(np.round(
                sum(item.get("glycemicIndex", 0) * item.get("nutrients", {}).get("netCarbohydrates", item.get("nutrients", {}).get("carbohydrates", 0.0))
                    for item in decomposed_items) / total_net_carbs
            ))
        else:
            weighted_gi = 0

        return {
            "totalWeightGrams": total_weight,
            "totalGlycemicLoad": total_gl,
            "glycemicLoadCategory": gl_category,
            "weightedGlycemicIndex": weighted_gi,
            "itemCount": len(decomposed_items),
            "nutrients": aggregated_nutrients
        }

    @classmethod
    def list_catalog(cls) -> List[Dict[str, Any]]:
        """Returns summarized catalog metadata for auto-completion and search."""
        catalog_items = []
        for key, entry in cls.NUTRITION_CATALOG.items():
            catalog_items.append({
                "canonicalKey": key,
                "displayName": entry["displayName"],
                "category": entry["category"],
                "standardServing": entry["standardServing"],
                "servingUnit": entry["servingUnit"],
                "servingWeightGrams": entry["servingWeightGrams"],
                "glycemicIndex": entry.get("gi", 0),
                "calories": entry["nutrientsPerServing"].get("calories", 0),
                "carbohydrates": entry["nutrientsPerServing"].get("carbohydrates", 0),
                "proteins": entry["nutrientsPerServing"].get("proteins", 0),
                "fats": entry["nutrientsPerServing"].get("fats", 0),
            })
        return sorted(catalog_items, key=lambda x: x["displayName"])


# Global singleton instance
nutrition_db = BioNutritionalDatabase()

