import { initializeApp, cert, getApps } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getMessaging } from 'firebase-admin/messaging';
import dotenv from 'dotenv';
import axios from 'axios';
import fs from 'fs';

dotenv.config();

let isFirebaseInitialized = false;
let messagingService = null;
let authService = null;
let resolvedProjectId = 'biosyncai-fd8a2';

if (process.env.FIREBASE_SERVICE_ACCOUNT) {
  try {
    const rawVal = process.env.FIREBASE_SERVICE_ACCOUNT.trim();
    let serviceAccount = null;

    if (rawVal.startsWith('{')) {
      serviceAccount = JSON.parse(rawVal);
    } else if (fs.existsSync(rawVal)) {
      serviceAccount = JSON.parse(fs.readFileSync(rawVal, 'utf8'));
    } else {
      try {
        const decoded = Buffer.from(rawVal, 'base64').toString('utf8');
        if (decoded.startsWith('{')) {
          serviceAccount = JSON.parse(decoded);
        }
      } catch (b64Err) {}
    }

    if (serviceAccount && serviceAccount.private_key) {
      serviceAccount.private_key = serviceAccount.private_key.replace(/\\n/g, '\n');
      if (serviceAccount.project_id) {
        resolvedProjectId = serviceAccount.project_id;
      }

      const app = getApps().length === 0
        ? initializeApp({ credential: cert(serviceAccount), projectId: resolvedProjectId })
        : getApps()[0];

      authService = getAuth(app);
      messagingService = getMessaging(app);
      isFirebaseInitialized = true;
      console.log(`[Firebase] Admin Initialized Successfully with Auth & Messaging for project: ${resolvedProjectId}`);
    } else {
      console.log('[Firebase] Service account credential not structured as expected.');
    }
  } catch (err) {
    console.warn('[Firebase] Service Account initialization warning:', err.message);
  }
} else {
  console.log('[Firebase] FIREBASE_SERVICE_ACCOUNT not configured.');
}

/**
 * Verifies a Firebase ID Token generated by Firebase Google Phone Auth
 * @param {string} idToken
 * @returns {Promise<{success: boolean, decodedToken?: object, phoneNumber?: string, uid?: string, message?: string}>}
 */
export const verifyFirebaseIdToken = async (idToken) => {
  if (!idToken) {
    return { success: false, message: 'No Firebase ID token provided' };
  }

  if (!isFirebaseInitialized || !authService) {
    return { success: false, message: 'Firebase Admin Auth is not initialized on the server.' };
  }

  try {
    const decodedToken = await authService.verifyIdToken(idToken.trim());
    return {
      success: true,
      decodedToken,
      phoneNumber: decodedToken.phone_number || null,
      uid: decodedToken.uid,
      email: decodedToken.email || null,
    };
  } catch (err) {
    console.warn('[Firebase Auth] verifyIdToken validation failed:', err.message);
    return { success: false, message: err.message };
  }
};

/**
 * Creates a Firebase Custom Token signed with Google credentials
 * @param {string} uid
 * @param {object} claims
 */
export const createFirebaseCustomToken = async (uid, claims = {}) => {
  if (!isFirebaseInitialized || !authService || !uid) return null;
  try {
    return await authService.createCustomToken(uid.toString(), claims);
  } catch (err) {
    console.warn('[Firebase Auth] createCustomToken warning:', err.message);
    return null;
  }
};

/**
 * Returns public Firebase project configuration for client reference
 */
export const getFirebaseProjectConfig = () => {
  return {
    projectId: resolvedProjectId,
    authDomain: `${resolvedProjectId}.firebaseapp.com`,
    isInitialized: isFirebaseInitialized,
  };
};

/**
 * Universal Push Notification Dispatcher
 * Supports Expo Push Tokens (ExponentPushToken[...] / ExpoPushToken[...]) and Native FCM Tokens
 */
export const sendPushNotification = async (targetToken, title, body, data = {}) => {
  if (!targetToken) return null;

  // 1. Expo Push Notification Dispatch (Expo Go / Production Expo Apps)
  if (
    typeof targetToken === 'string' &&
    (targetToken.startsWith('ExponentPushToken[') || targetToken.startsWith('ExpoPushToken['))
  ) {
    try {
      const response = await axios.post(
        'https://exp.host/--/api/v2/push/send',
        {
          to: targetToken,
          sound: 'default',
          title,
          body,
          data,
          priority: 'high',
          channelId: 'biosync-critical',
          badge: 1,
        },
        {
          headers: {
            'Accept': 'application/json',
            'Accept-Encoding': 'gzip, deflate',
            'Content-Type': 'application/json',
          },
          timeout: 8000,
        }
      );
      console.log(`[ExpoPush] Push notification delivered to ${targetToken.substring(0, 24)}...: "${title}"`);
      return response.data;
    } catch (err) {
      console.warn('[ExpoPush] Push delivery warning:', err?.response?.data || err.message);
      return null;
    }
  }

  // 2. Native FCM Dispatch via Firebase Admin (Standalone Builds)
  if (!isFirebaseInitialized || !messagingService) {
    return null;
  }

  // FCM v1 requires all custom data payload values to be strings
  const stringifiedData = Object.entries(data).reduce((acc, [key, val]) => {
    acc[key] = typeof val === 'string' ? val : JSON.stringify(val);
    return acc;
  }, {});

  try {
    const payload = {
      notification: { title, body },
      data: stringifiedData,
      token: targetToken,
      android: {
        priority: 'high',
        notification: { sound: 'default', channelId: 'biosync-critical' },
      },
      apns: {
        payload: {
          aps: {
            sound: 'default',
            badge: 1,
          },
        },
      },
    };

    const fcmRes = await messagingService.send(payload);
    console.log(`[FCM] Native push delivered to ${targetToken.substring(0, 16)}...: "${title}"`);
    return fcmRes;
  } catch (error) {
    console.warn('[FCM] Dispatch warning:', error.message);
    return null;
  }
};

export const adminAuth = authService;
export const adminMessaging = messagingService;

export default {
  isInitialized: () => isFirebaseInitialized,
  verifyFirebaseIdToken,
  createFirebaseCustomToken,
  getFirebaseProjectConfig,
  sendPushNotification,
};